package com.system.pojo;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Cpno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String cpno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.Ccredit
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private Short ccredit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cno
     *
     * @return the value of course.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cno
     *
     * @param cno the value for course.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cname
     *
     * @return the value of course.Cname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cname
     *
     * @param cname the value for course.Cname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Cpno
     *
     * @return the value of course.Cpno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getCpno() {
        return cpno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Cpno
     *
     * @param cpno the value for course.Cpno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCpno(String cpno) {
        this.cpno = cpno == null ? null : cpno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.Ccredit
     *
     * @return the value of course.Ccredit
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public Short getCcredit() {
        return ccredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.Ccredit
     *
     * @param ccredit the value for course.Ccredit
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCcredit(Short ccredit) {
        this.ccredit = ccredit;
    }

    public Course(String cno, String cname, String cpno, Short ccredit) {
        this.cno = cno;
        this.cname = cname;
        this.cpno = cpno;
        this.ccredit = ccredit;
    }

    public Course() {
    }

    @Override
    public String toString() {
        return "Course{" +
                "cno='" + cno + '\'' +
                ", cname='" + cname + '\'' +
                ", cpno='" + cpno + '\'' +
                ", ccredit=" + ccredit +
                '}';
    }
}