package com.system.pojo;

public class SC {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Sno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String cno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.Grade
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private Short grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Sno
     *
     * @return the value of sc.Sno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Sno
     *
     * @param sno the value for sc.Sno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setSno(String sno) {
        this.sno = sno == null ? null : sno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Cno
     *
     * @return the value of sc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Cno
     *
     * @param cno the value for sc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.Grade
     *
     * @return the value of sc.Grade
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public Short getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.Grade
     *
     * @param grade the value for sc.Grade
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setGrade(Short grade) {
        this.grade = grade;
    }

    public SC(String sno, String cno, Short grade) {
        this.sno = sno;
        this.cno = cno;
        this.grade = grade;
    }

    public SC() {
    }

    @Override
    public String toString() {
        return "SC{" +
                "sno='" + sno + '\'' +
                ", cno='" + cno + '\'' +
                ", grade=" + grade +
                '}';
    }
}