package com.system.pojo;

public class TC {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Tno
     *
     * @return the value of tc.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Tno
     *
     * @param tno the value for tc.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.Cno
     *
     * @return the value of tc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.Cno
     *
     * @param cno the value for tc.Cno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setCno(String cno) {
        this.cno = cno == null ? null : cno.trim();
    }

    public TC(String tno, String cno) {
        this.tno = tno;
        this.cno = cno;
    }

    public TC() {
    }

    @Override
    public String toString() {
        return "TC{" +
                "tno='" + tno + '\'' +
                ", cno='" + cno + '\'' +
                '}';
    }
}