package com.system.pojo;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String tno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tsex
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String tsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tage
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private Short tage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tdept
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private String tdept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.Tsalary
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    private Integer tsalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tno
     *
     * @return the value of teacher.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tno
     *
     * @param tno the value for teacher.Tno
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTno(String tno) {
        this.tno = tno == null ? null : tno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tname
     *
     * @return the value of teacher.Tname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tname
     *
     * @param tname the value for teacher.Tname
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tsex
     *
     * @return the value of teacher.Tsex
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getTsex() {
        return tsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tsex
     *
     * @param tsex the value for teacher.Tsex
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTsex(String tsex) {
        this.tsex = tsex == null ? null : tsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tage
     *
     * @return the value of teacher.Tage
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public Short getTage() {
        return tage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tage
     *
     * @param tage the value for teacher.Tage
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTage(Short tage) {
        this.tage = tage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tdept
     *
     * @return the value of teacher.Tdept
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public String getTdept() {
        return tdept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tdept
     *
     * @param tdept the value for teacher.Tdept
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTdept(String tdept) {
        this.tdept = tdept == null ? null : tdept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.Tsalary
     *
     * @return the value of teacher.Tsalary
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public Integer getTsalary() {
        return tsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.Tsalary
     *
     * @param tsalary the value for teacher.Tsalary
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    public void setTsalary(Integer tsalary) {
        this.tsalary = tsalary;
    }

    public Teacher(String tno, String tname, String tsex, Short tage, String tdept, Integer tsalary) {
        this.tno = tno;
        this.tname = tname;
        this.tsex = tsex;
        this.tage = tage;
        this.tdept = tdept;
        this.tsalary = tsalary;
    }

    public Teacher() {
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "tno='" + tno + '\'' +
                ", tname='" + tname + '\'' +
                ", tsex='" + tsex + '\'' +
                ", tage=" + tage +
                ", tdept='" + tdept + '\'' +
                ", tsalary=" + tsalary +
                '}';
    }
}