package com.system.mapper;

import com.system.pojo.SC;
import com.system.pojo.SCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    long countByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int deleteByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insert(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insertSelective(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    List<SC> selectByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") SC record, @Param("example") SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExample(@Param("record") SC record, @Param("example") SCExample example);
}