package com.system.mapper;

import com.system.pojo.Suser;
import com.system.pojo.SuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    long countByExample(SuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int deleteByExample(SuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insert(Suser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insertSelective(Suser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    List<Suser> selectByExample(SuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") Suser record, @Param("example") SuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suser
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExample(@Param("record") Suser record, @Param("example") SuserExample example);

}