package com.system.mapper;

import com.system.pojo.TC;
import com.system.pojo.TCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    long countByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int deleteByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insert(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int insertSelective(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    List<TC> selectByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExampleSelective(@Param("record") TC record, @Param("example") TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbg.generated Sun Nov 06 18:52:56 CST 2022
     */
    int updateByExample(@Param("record") TC record, @Param("example") TCExample example);
}